DROP TABLE IF EXISTS consumers;

CREATE TABLE consumers (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name TEXT NOT NULL, 
    consumer_id UUID NOT NULL
);